[package]
name = "rust_codewar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
itertools = "0.10.5"
rand = "0.8.1"
float_eq = "1.0.1"
min-max = "0.1"
regex = "1.7.1"
once_cell = "1.17.1"