pub mod spin_words;
pub mod no_space;
pub mod sort_by_last_char;
pub mod what_century;
pub mod reverse_words;
pub mod fix_string_case;
pub mod reverse_words_2;
pub mod repeat_str;
mod reverse_letters;
mod high_and_low;
mod get_count;
mod to_csv_text;
mod spoonerize;
mod string_to_number;
mod remove_char;
mod disemvowel;
