pub mod spin_words;
pub mod no_space;
pub mod sort_by_last_char;
pub mod what_century;
pub mod reverse_words;
pub mod fix_string_case;
pub mod reverse_words_2;
pub mod repeat_str;
mod reverse_letters;
mod high_and_low;
mod get_count;
mod to_csv_text;
mod spoonerize;
mod string_to_number;
mod remove_char;
mod disemvowel;
mod string_end_with;
mod freq_seq;
mod abbrev_name;
mod string_to_array;
mod high;
mod is_valid_ip;
mod greet;
mod camel_case;
mod next_bigger_number;
mod longest_repetition;
mod to_camel_case;
mod solve;
mod digital_root;
mod time_correct;
mod multi_table;
mod string_to_industrial;
mod to_alternating_case;
mod create_phone_number;
mod maskify;
mod valid_parentheses;
mod count;
mod to_nato;
mod switcher;
