pub mod sum_cubes;
pub mod descending_order;
pub mod bool_to_word;
pub mod race_podium;
mod _if;
mod litres;
mod find_difference;
mod zero_fuel;
mod greet;
mod odd_count;
mod divisible_count;
mod heron;
mod pofi;
mod summation;
mod past;
mod find_short;
mod basic_op;
mod incrementer;
mod nb_dig;
mod zip_with;
mod narcissistic;
mod longest_consec;
mod unique_in_order;
mod get_pins;
mod rgb;
mod range_extraction;
