pub mod largest;
pub mod number_of_pairs;
pub mod add_length;
pub mod invert;
pub mod sum_of_minimums;
pub mod ordered_count;
mod remove_smallest;
mod sort_numbers;
mod minimum_maximum;
mod find_average;
